# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_skills_legend',
            field=models.BooleanField(default=False),
        ),
    ]
