# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('remote', models.CharField(choices=[(b'dd', b"Don't display"), (b'rr', b'Remote-ready'), (b'ro', b'Remote-only'), (b'nr', b'No remote')], default=b'dd', max_length=2)),
                ('relocation', models.CharField(choices=[(b'dd', b"Don't display"), (b'rr', b'Relocation-ready'), (b'nr', b'No relocation')], default=b'dd', max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('languages', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[(b'dd', b"Don't display"), (b'ma', b'Male'), (b'fe', b'Female'), (b'tr', b'Trans*')], default=b'dd', max_length=2)),
                ('introduction', models.TextField(blank=True)),
                ('willing_to_try', models.TextField(blank=True)),
                ('other_details', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.Cv')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=20)),
                ('website', models.CharField(blank=True, max_length=1000)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('stack', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.Cv')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_groups', to='core.Cv')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.SkillGroup'),
        ),
    ]
