# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
