# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181119_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='cv',
            name='skills_intro',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
