# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181225_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
